DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE(
  ID INT NOT NULL AUTO_INCREMENT
  , FIRST_NAME VARCHAR(60) NOT NULL
  , LAST_NAME VARCHAR(40) NOT NULL
  , BIRTH_DATE DATE
  , NATIONALITY VARCHAR(30) NOT NULL
  , RATING INT
  , DESCRIPTION VARCHAR(200)
  , PRIMARY KEY (ID)
);